### ISSUE TITLE
projects output is empty

### ISSUE THREAD

**Issue by jonseymour** [CircleCI-Public/CircleCI-Env-Inspector#22]
When I run this (after generating a new API token), I am getting a dump of all the contexts for the organisation as expected, but the projects array is empty whereas I expected it to list at least the 8 organisation projects followed by the API token holder.

```
Getting Contexts Data...
Getting Projects Data...
Getting Projects Variables...
Log created at circleci-data.json
Extracting data from container...
Cleaning up...
Done.
```

Output:

```
{
...
  "projects": [],
  "unavailable": []
}

```

**Comment by BenCoffeed** [comment]
I've done a little bit of digging. I'm using GitHub as the VCS provider. I've identified that if I remove the filter [here](https://github.com/CircleCI-Public/CircleCI-Env-Inspector/blob/434a03bbf55a7073a796792808f7c5133d2d78a7/index.js#L222), I get an incomplete list of projects without any environment variables. This leads me to believe the root cause of this issue is with the handling of pagination from the GitHub API. I'm continuing to dig through to find a workaround and/or solution.

**Comment by BenCoffeed** [comment]
After more digging, it appears that the issue is not pagination, but rather permissions. It does not appear private repositories are being included in the list. Attempting to modify to use the search API endpoint and troubleshoot permissions issues.

**Comment by BenCoffeed** [comment]
@jonseymour. I tracked down my issue. The issue is that if you are trying to generate a PAT for accessing GitHub organizations, the organization must [enroll in an access token policy](https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization). 

Once that is configured, create a new fine-grained PAT with read-only access to metadata and make sure to set the owner to the organization.

I think the actual "Fix" for this is adding more instructions on how to properly authenticate for GitHub.

**Comment by jonseymour** [comment]
@BenCoffeed thanks for the analysis. 

FWIW, neither the organisation or the token holder was enrolled in or using fine-grained personal access tokens. 

I ended up enrolling the organisation and enabled access with classic personal access tokens.

When I did this, the I was able to see the list of non-circle CI managed projects in "unavailable" but the projects list was still empty.

**Comment by jonseymour** [comment]
No change when I created a fine-grained access token. 

I checked the organisation to check that the token was active.

I granted read on projects and read on repository metadata for all repositories to the token.

<img width="1212" alt="Screenshot 2023-01-10 at 9 58 57 am" src="https://user-images.githubusercontent.com/207131/211425189-70201cf6-59de-4858-8254-5502d08f5875.png">

**Comment by jonseymour** [comment]
I should also note that I don't have any project-level variables - we do use contexts. What I was expecting to see in the project lists was a list of the managed projects and the ssh user keys that they use.

**Comment by jonseymour** [comment]
Ok, I added a project variable and now the project I added the variable is listed, but the ssh keys are not listed.

**Comment by BenCoffeed** [comment]
That is the expected behavior. There is a filter step which filters the list of repos/projects based on projects that have project level environment variables configured. I do not believe that this tool reports on users. I did see some allusions to a beta account management feature that allowed you to have central control over access while googling. I'm away from my workstation at the moment, but the article identified that the feature was only available via request from CircleCI support.

**Comment by jonseymour** [comment]
Ok, I had incorrectly assumed that the project-level SSH keys would be listed as these are an important part of the set of credentials that need to be rotated. The keys I am referring to are the ones listed in the SSH keys section of the UI

<img width="1241" alt="Screenshot 2023-01-10 at 10 35 13 am" src="https://user-images.githubusercontent.com/207131/211429883-385d6c4e-515e-4614-90d9-e3a434068d83.png">

From a usability point of view, it might raise less questions if the projects were listed with an empty list of variables rather than simply eliding projects that have no variables. This would at least provide some assurance that the tool has identified the projects as candidates for listing.

**Comment by jonseymour** [comment]
@BenCoffeed  - feel free to close this without further response.
